import { mergeAssetsWithRuntimeState, resolveRuntimeAssetIdentity } from "@/widgets/map-stage/use-operations-runtime-sync";

describe("operations runtime asset identity", () => {
  it("keeps a neutral device identifier for synthetic assets instead of inventing a global callsign", () => {
    const asset = {
      id: "asset-auto-e009171d4f4b32e2",
      callsign: "ASSET-AUTO-E009171D4F4B32E2",
      name: "AUTO DEVICE-5",
      assetType: "ground",
      batteryPct: 50,
      position: { lat: -35.7, lon: -75.6 },
      status: "nominal",
      updatedAt: "2026-06-12T12:00:00.000Z",
    } as never;

    const device = {
      id: "device-5",
      assetId: asset.id,
      metadata: {
        callsign: "Guardian Truck 5",
      },
    } as never;

    const identity = resolveRuntimeAssetIdentity(asset, device, null, null);

    expect(identity).toEqual({
      callsign: "device-5",
      name: "device-5",
    });
  });

  it("ignores autogenerated runtime names and keeps the device id as the secondary label", () => {
    const assets = [{
      id: "asset-auto-e009171d4f4b32e2",
      kind: "asset",
      version: 1,
      updatedAt: "2026-06-12T12:00:00.000Z",
      source: "runtime",
      name: "AUTO DEVICE-5",
      callsign: "ASSET-AUTO-E009171D4F4B32E2",
      assetType: "ground",
      status: "nominal",
      affiliation: "friendly",
      position: { lat: -35.798, lon: -75.6693 },
      mission: "Tracking",
    }] as never[];

    const devices = [{
      id: "device-5",
      assetId: "asset-auto-e009171d4f4b32e2",
      metadata: {
        callsign: "Guardian Truck 5",
      },
    }] as never[];

    const telemetry = [{
      id: "telemetry-1",
      deviceId: "device-5",
      assetId: "asset-auto-e009171d4f4b32e2",
      batteryPct: 77,
      signalQuality: 88,
      timestamp: "2026-06-12T12:01:00.000Z",
      position: { lat: -35.798, lon: -75.6693 },
      rawPayload: {
        name: "AUTO DEVICE-5",
      },
    }] as never[];

    const merged = mergeAssetsWithRuntimeState(assets, devices, [], telemetry);

    expect(merged[0]).toEqual(expect.objectContaining({
      callsign: "device-5",
      name: "device-5",
      batteryPct: 77,
      linkQualityPct: 88,
    }));
  });

  it("uses telemetry linked by device id when assetId is missing", () => {
    const assets = [{
      id: "asset-auto-9bbc17b907176dc3",
      kind: "asset",
      version: 1,
      updatedAt: "2026-06-12T12:00:00.000Z",
      source: "runtime",
      name: "device-6",
      callsign: "DEVICE-6",
      assetType: "ground",
      status: "nominal",
      affiliation: "friendly",
      position: { lat: -38.838, lon: -75.6693, headingDeg: 20, speedMps: 8 },
      mission: "Tracking",
      batteryPct: 55,
      linkQualityPct: 20,
    }] as never[];

    const devices = [{
      id: "device-6",
      assetId: "asset-auto-9bbc17b907176dc3",
      metadata: {},
    }] as never[];

    const telemetry = [{
      id: "telemetry-6",
      deviceId: "device-6",
      assetId: null,
      batteryPct: 92,
      signalQuality: 61,
      timestamp: "2026-06-12T12:01:00.000Z",
      position: { lat: -38.838, lon: -75.6693, headingDeg: 90, speedMps: 30 },
      rawPayload: {},
    }] as never[];

    const merged = mergeAssetsWithRuntimeState(assets, devices, [], telemetry);

    expect(merged[0]).toEqual(expect.objectContaining({
      batteryPct: 92,
      linkQualityPct: 61,
      updatedAt: "2026-06-12T12:01:00.000Z",
    }));
  });

  it("preserves heading and speed from telemetry when track updates only move lat lon", () => {
    const assets = [{
      id: "asset-auto-9bbc17b907176dc3",
      kind: "asset",
      version: 1,
      updatedAt: "2026-06-12T12:00:00.000Z",
      source: "runtime",
      name: "device-6",
      callsign: "DEVICE-6",
      assetType: "ground",
      status: "nominal",
      affiliation: "friendly",
      position: { lat: -38.838, lon: -75.6693, headingDeg: 20, speedMps: 8 },
      mission: "Tracking",
    }] as never[];

    const devices = [{
      id: "device-6",
      assetId: "asset-auto-9bbc17b907176dc3",
      metadata: {},
    }] as never[];

    const tracks = [{
      id: "track-device-6",
      assetId: "asset-auto-9bbc17b907176dc3",
      deviceId: "device-6",
      timestamp: "2026-06-12T12:02:00.000Z",
      position: { lat: -38.9, lon: -75.7 },
      status: "active",
      metadata: {},
      updatedAt: "2026-06-12T12:02:00.000Z",
    }] as never[];

    const telemetry = [{
      id: "telemetry-6",
      deviceId: "device-6",
      assetId: null,
      batteryPct: 92,
      signalQuality: 61,
      timestamp: "2026-06-12T12:01:00.000Z",
      position: { lat: -38.838, lon: -75.6693, headingDeg: 90, speedMps: 30 },
      rawPayload: {},
    }] as never[];

    const merged = mergeAssetsWithRuntimeState(assets, devices, tracks, telemetry);

    expect(merged[0]).toEqual(expect.objectContaining({
      position: expect.objectContaining({
        lat: -38.9,
        lon: -75.7,
        headingDeg: 90,
        speedMps: 30,
      }),
    }));
  });

  it("uses the newest telemetry record when records arrive out of order", () => {
    const assets = [{
      id: "asset-auto-9bbc17b907176dc3",
      kind: "asset",
      version: 1,
      updatedAt: "2026-06-12T12:00:00.000Z",
      source: "runtime",
      name: "device-6",
      callsign: "DEVICE-6",
      assetType: "ground",
      status: "nominal",
      affiliation: "friendly",
      position: { lat: -38.838, lon: -75.6693, headingDeg: 20, speedMps: 8 },
      mission: "Tracking",
      batteryPct: 55,
      linkQualityPct: 20,
    }] as never[];

    const devices = [{
      id: "device-6",
      assetId: "asset-auto-9bbc17b907176dc3",
      metadata: {},
    }] as never[];

    const telemetry = [
      {
        id: "telemetry-old",
        deviceId: "device-6",
        assetId: null,
        batteryPct: 10,
        signalQuality: 12,
        timestamp: "2026-06-12T12:00:10.000Z",
        position: { lat: -38.838, lon: -75.6693, headingDeg: 10, speedMps: 2 },
        rawPayload: {},
      },
      {
        id: "telemetry-new",
        deviceId: "device-6",
        assetId: null,
        batteryPct: 93,
        signalQuality: 78,
        timestamp: "2026-06-12T12:05:10.000Z",
        position: { lat: -38.84, lon: -75.67, headingDeg: 135, speedMps: 40 },
        rawPayload: {},
      },
    ] as never[];

    const merged = mergeAssetsWithRuntimeState(assets, devices, [], telemetry);

    expect(merged[0]).toEqual(expect.objectContaining({
      batteryPct: 93,
      linkQualityPct: 78,
      updatedAt: "2026-06-12T12:05:10.000Z",
      position: expect.objectContaining({
        headingDeg: 135,
        speedMps: 40,
      }),
    }));
  });
});
