"use client";

import { useEffect, useState } from "react";
import { browserApiClient } from "@/lib/api";
import { createRealtimeClient, type RealtimeConnectionStatus, type RealtimeEventMap } from "@/lib/ws";
import type { MapStageBootstrap } from "@/shared/contracts/operations-map";
import type { Alert, Asset, Command, Device, Geofence, MapLayer, Mission, TelemetryRecord, Track } from "@/types/domain";
import {
  toOperationalAlert,
  toOperationalScenario,
  toTelemetryRecord,
  toTrack,
  toTrackHistoryPoint,
} from "@/types/domain";
import type { AuthUserDto, TrackHistoryDto } from "@/types/api";
import { loadMapLayers } from "./use-operations-map-layers";

type AssetTrackPoint = {
  lat: number;
  lon: number;
};

function sortTelemetryRecordsByTimestampDesc(records: TelemetryRecord[]) {
  return [...records].sort((left, right) =>
    new Date(right.timestamp).getTime() - new Date(left.timestamp).getTime(),
  );
}

function mergeTelemetryRecords(current: TelemetryRecord[], incoming: TelemetryRecord[]) {
  const byId = new Map<string, TelemetryRecord>();

  for (const item of [...incoming, ...current]) {
    byId.set(item.id, item);
  }

  return sortTelemetryRecordsByTimestampDesc([...byId.values()]).slice(0, 500);
}

function mergeAssetPosition(asset: Asset, track: Track | null, telemetry: TelemetryRecord | null) {
  return {
    lat: track?.position.lat ?? telemetry?.position.lat ?? asset.position.lat,
    lon: track?.position.lon ?? telemetry?.position.lon ?? asset.position.lon,
    altM: track?.position.altM ?? telemetry?.position.altM ?? asset.position.altM,
    headingDeg: track?.position.headingDeg ?? telemetry?.position.headingDeg ?? asset.position.headingDeg,
    speedMps: track?.position.speedMps ?? telemetry?.position.speedMps ?? asset.position.speedMps,
  };
}

function asRecord(value: unknown): Record<string, unknown> | null {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return null;
}

function asText(value: unknown) {
  if (typeof value !== "string") {
    return null;
  }

  const normalized = value.trim();
  return normalized.length > 0 ? normalized : null;
}

function readFirstText(sources: Array<Record<string, unknown>>, keys: string[]) {
  for (const source of sources) {
    for (const key of keys) {
      const value = asText(source[key]);
      if (value) {
        return value;
      }
    }
  }

  return null;
}

function isSyntheticAssetIdentifier(value: string) {
  return /^asset-auto-/i.test(value) || /^asset[_-]auto/i.test(value);
}

function isAutoGeneratedDisplayName(value: string) {
  return /^auto device(?:[-\s]|$)/i.test(value)
    || /^asset-auto-/i.test(value)
    || /^asset[_-]auto/i.test(value);
}

export function resolveRuntimeAssetIdentity(
  asset: Asset,
  device: Device | null,
  track: Track | null,
  telemetry: TelemetryRecord | null,
) {
  const metadata = asRecord(device?.metadata) ?? {};
  const rawPayload = asRecord(telemetry?.rawPayload) ?? {};
  const sources = [rawPayload, metadata];
  const deviceIdentifier = device?.id ?? telemetry?.deviceId ?? track?.deviceId ?? null;
  const preferredName = readFirstText(sources, [
    "name",
    "assetName",
    "asset_name",
    "deviceName",
    "device_name",
    "displayName",
    "display_name",
    "label",
    "title",
  ]);

  if (deviceIdentifier && isSyntheticAssetIdentifier(asset.callsign)) {
    return {
      callsign: device?.externalId ?? deviceIdentifier,
      name: deviceIdentifier,
    };
  }

  return {
    callsign: asset.callsign,
    name: preferredName && !isAutoGeneratedDisplayName(preferredName) ? preferredName : asset.name,
  };
}

function mergeUniqueTrackPoints(existing: AssetTrackPoint[], incoming: AssetTrackPoint[]) {
  const merged = [...existing, ...incoming];
  const seen = new Set<string>();

  return merged.filter((point) => {
    const key = `${point.lat.toFixed(6)}:${point.lon.toFixed(6)}`;
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
}

function buildTrackMap(history: TrackHistoryDto[], currentTracks: Track[]) {
  const nextMap: Record<string, AssetTrackPoint[]> = {};

  for (const point of history.map(toTrackHistoryPoint)) {
    nextMap[point.assetId] ??= [];
    nextMap[point.assetId].push({
      lat: point.position.lat,
      lon: point.position.lon,
    });
  }

  for (const track of currentTracks) {
    nextMap[track.assetId] = mergeUniqueTrackPoints(nextMap[track.assetId] ?? [], [{
      lat: track.position.lat,
      lon: track.position.lon,
    }]);
  }

  return nextMap;
}

function pickLatestTelemetryRecord(records: TelemetryRecord[]) {
  let latest: TelemetryRecord | null = null;

  for (const record of records) {
    if (!latest || new Date(record.timestamp).getTime() > new Date(latest.timestamp).getTime()) {
      latest = record;
    }
  }

  return latest;
}

export function mergeAssetsWithRuntimeState(
  assets: MapStageBootstrap["snapshot"]["assets"],
  devices: Device[],
  tracks: Track[],
  telemetry: TelemetryRecord[],
) {
  const deviceByAssetId = new Map(
    devices
      .filter((device) => device.assetId)
      .map((device) => [device.assetId as string, device]),
  );

  return assets.map((asset) => {
    const track = tracks.find((candidate) => candidate.assetId === asset.id) ?? null;
    const device = deviceByAssetId.get(asset.id) ?? null;
    const latestTelemetry = pickLatestTelemetryRecord(
      telemetry.filter((candidate) =>
        candidate.assetId === asset.id || (device ? candidate.deviceId === device.id : false),
      ),
    );
    const identity = resolveRuntimeAssetIdentity(asset, device, track, latestTelemetry);

    if (!track && !latestTelemetry && !device && identity.callsign === asset.callsign && identity.name === asset.name) {
      return asset;
    }

    return {
      ...asset,
      callsign: identity.callsign,
      name: identity.name,
      position: mergeAssetPosition(asset, track, latestTelemetry),
      batteryPct: latestTelemetry?.batteryPct ?? asset.batteryPct,
      linkQualityPct: latestTelemetry?.signalQuality ?? asset.linkQualityPct,
      updatedAt: track?.timestamp ?? latestTelemetry?.timestamp ?? asset.updatedAt,
    };
  });
}

export function useOperationsRuntimeSync(options: {
  initialBootstrap: MapStageBootstrap;
  replaceMapLayers: (nextLayers: MapLayer[]) => void;
}) {
  const { initialBootstrap, replaceMapLayers } = options;
  const [sessionUser, setSessionUser] = useState<AuthUserDto | null>(null);
  const [connectionStatus, setConnectionStatus] = useState<RealtimeConnectionStatus>("connecting");
  const [devices, setDevices] = useState<Device[]>([]);
  const [tracks, setTracks] = useState<Track[]>([]);
  const [telemetry, setTelemetry] = useState<TelemetryRecord[]>([]);
  const [commands, setCommands] = useState<Command[]>([]);
  const [alerts, setAlerts] = useState<Alert[]>(initialBootstrap.snapshot.alerts);
  const [missions, setMissions] = useState<Mission[]>([]);
  const [geofences, setGeofences] = useState<Geofence[]>([]);
  const [assetTracks, setAssetTracks] = useState<Record<string, AssetTrackPoint[]>>(() =>
    Object.fromEntries(initialBootstrap.snapshot.assets.map((asset) => [asset.id, [{
      lat: asset.position.lat,
      lon: asset.position.lon,
    }]])),
  );
  const [snapshot, setSnapshot] = useState(initialBootstrap.snapshot);

  useEffect(() => {
    let cancelled = false;

    async function refreshAlerts() {
      const nextAlerts = await browserApiClient.get("/alerts") as never[];

      if (cancelled) {
        return;
      }

      const mappedAlerts = nextAlerts.map(toOperationalAlert);
      setAlerts(mappedAlerts);
      setSnapshot((current) => ({
        ...current,
        alerts: mappedAlerts,
      }));
    }

    async function refreshMissions() {
      const nextMissions = await browserApiClient.get("/missions") as Mission[];

      if (!cancelled) {
        setMissions(nextMissions);
      }
    }

    async function refreshCommands() {
      const nextCommands = await browserApiClient.get("/commands") as Command[];

      if (!cancelled) {
        setCommands(nextCommands);
      }
    }

    async function refreshDevices(deviceId?: string) {
      if (!deviceId) {
        return;
      }

      const nextDevice = await browserApiClient.get(`/devices/${deviceId}`) as Device;

      if (!cancelled) {
        setDevices((current) => [nextDevice, ...current.filter((item) => item.id !== nextDevice.id)]);
      }
    }

    async function refreshTelemetry(deviceId: string) {
      const nextTelemetry = await browserApiClient.get(`/telemetry/${deviceId}`) as never[];

      if (!cancelled) {
        const mappedTelemetry = sortTelemetryRecordsByTimestampDesc(nextTelemetry.map(toTelemetryRecord));
        setTelemetry((current) => {
          const filtered = current.filter((item) => item.deviceId !== deviceId);
          return mergeTelemetryRecords(filtered, mappedTelemetry);
        });
      }
    }

    async function refreshMapLayerState() {
      replaceMapLayers(await loadMapLayers());
    }

    async function bootstrapRuntime() {
      const [
        sessionResponse,
        nextSnapshot,
        nextDevices,
        nextCurrentTracks,
        nextTrackHistory,
        nextTelemetry,
        nextCommands,
        nextMissions,
        nextGeofences,
        nextMapLayers,
      ] = await Promise.all([
        fetch("/api/session/me", { cache: "no-store", credentials: "same-origin" }),
        browserApiClient.get("/v1/operations/snapshot"),
        browserApiClient.get("/devices"),
        browserApiClient.get("/tracks/current"),
        browserApiClient.get("/tracks/history"),
        browserApiClient.get("/telemetry"),
        browserApiClient.get("/commands"),
        browserApiClient.get("/missions"),
        browserApiClient.get("/geofences"),
        loadMapLayers(),
      ]);

      if (cancelled) {
        return;
      }

      if (sessionResponse.ok) {
        const sessionPayload = await sessionResponse.json() as { user: AuthUserDto };
        setSessionUser(sessionPayload.user);
      }

      const mappedSnapshot = toOperationalScenario(nextSnapshot as never);
      const mappedTracks = (nextCurrentTracks as never[]).map(toTrack);
      const mappedTelemetry = sortTelemetryRecordsByTimestampDesc((nextTelemetry as never[]).map(toTelemetryRecord));

      setSnapshot(mappedSnapshot);
      setAlerts(mappedSnapshot.alerts);
      setDevices(nextDevices as Device[]);
      setTracks(mappedTracks);
      setTelemetry(mappedTelemetry);
      setCommands(nextCommands as Command[]);
      setMissions(nextMissions as Mission[]);
      setGeofences(nextGeofences as Geofence[]);
      replaceMapLayers(nextMapLayers);
      setAssetTracks(buildTrackMap(nextTrackHistory as TrackHistoryDto[], mappedTracks));
    }

    async function handleRealtimeEvent<K extends keyof RealtimeEventMap>(
      event: K,
      payload: RealtimeEventMap[K],
    ) {
      switch (event) {
        case "track.updated": {
          const nextPayload = payload as RealtimeEventMap["track.updated"];
          setTracks((current) => {
            const nextTrack: Track = {
              id: `track-${nextPayload.deviceId}`,
              assetId: nextPayload.assetId,
              deviceId: nextPayload.deviceId,
              timestamp: nextPayload.timestamp,
              position: {
                lat: nextPayload.lat,
                lon: nextPayload.lon,
              },
              status: "active",
              metadata: {},
              updatedAt: nextPayload.timestamp,
            };
            const filtered = current.filter((item) => item.deviceId !== nextPayload.deviceId);
            return [nextTrack, ...filtered];
          });

          setAssetTracks((current) => ({
            ...current,
            [nextPayload.assetId]: mergeUniqueTrackPoints(current[nextPayload.assetId] ?? [], [{
              lat: nextPayload.lat,
              lon: nextPayload.lon,
            }]),
          }));

          setSnapshot((current) => ({
            ...current,
            assets: current.assets.map((asset) => asset.id === nextPayload.assetId
              ? {
                  ...asset,
                  position: {
                    ...asset.position,
                    lat: nextPayload.lat,
                    lon: nextPayload.lon,
                  },
                  updatedAt: nextPayload.timestamp,
                }
              : asset),
          }));
          break;
        }
        case "telemetry.received":
          await refreshTelemetry((payload as RealtimeEventMap["telemetry.received"]).deviceId);
          break;
        case "device.status.changed":
          await refreshDevices((payload as RealtimeEventMap["device.status.changed"]).deviceId);
          break;
        case "command.status.changed":
          await refreshCommands();
          break;
        case "alert.created":
        case "alert.updated":
          await refreshAlerts();
          break;
        case "mission.updated":
          await refreshMissions();
          break;
        case "layer.updated":
          await refreshMapLayerState();
          break;
        default:
          break;
      }
    }

    void bootstrapRuntime();

    const realtimeClient = createRealtimeClient({
      onStatusChange: setConnectionStatus,
      onEvent(event, payload) {
        if (!cancelled) {
          void handleRealtimeEvent(event, payload);
        }
      },
    });

    realtimeClient.connect();

    return () => {
      cancelled = true;
      realtimeClient.disconnect();
    };
  }, [initialBootstrap.snapshot, replaceMapLayers]);

  return {
    alerts,
    assetTracks,
    commands,
    connectionStatus,
    devices,
    geofences,
    missions,
    sessionUser,
    setAlerts,
    setCommands,
    setDevices,
    setMissions,
    snapshot,
    telemetry,
    tracks,
  };
}
